#!/usr/bin/env bash

BIN="/opt/bin/vaultreader"
LOG="/var/log/vaultreader.log"

if [ -f "$BIN" ]; then
    chgrp devops "$BIN" || :
    chmod 2755 "$BIN" || :
fi

touch "$LOG"
chown root:devops "$LOG" || :
chmod 0664 "$LOG" || :